volumes: # тома для сохранения данных
  data-pg-obdsmo:
  pgadmin-data-obdsmo:

networks: # сеть docker
  postgres_network:
    driver: bridge

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile # файл сборки
    container_name: psql_obdsmo
    restart: always
    volumes:
      - data-pg-obdsmo:/var/lib/postgresql/data
    environment: # переменные окружения для работы psql
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck: # проверка работоспособности
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - postgres_network

  pgadmin: # веб интерфейс для работы с бд
    container_name: pgadmin_obdsmo
    image: elestio/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data-obdsmo:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_network
    depends_on:
      postgres:
        condition: service_healthy
